spring:
  application:
    name: projetoPI
  profiles:
    active: hml
#    active: dev
#    active: prod


# ================= ALTERAR PARA "PROD" NO AMBIENTE EM NUVEM ================= #

# ====== ALTERAR A SENHA DO BANCO DE DADOS "HML" PARA RODAR A APLICAÇÃO ====== #

# ============= TESTES DEVEM SER EXECUTADOS NO AMBIENTE DE "TEST" ============= #
